version: "3"

services:
    pg:
        image: mdillon/postgis:10-alpine
        container_name: 'imap_pg'
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            - POSTGRES_USER=${DB_DEFAULT_USER}
            - POSTGRES_DB=${DB_DEFAULT_NAME}
            - POSTGRES_PASSWORD=${DB_DEFAULT_PASSWORD}
        volumes:
            # TODO: find a way to make the volume path per environment
            - ~/data/impg:/var/lib/postgresql/data

    interactivemap:
        image: interactivemap:latest
        container_name: 'interactivemap'
        env_file:
            - prod.env
        depends_on:
            - pg

    staticapp:
        image: imap_static
        container_name: 'imap_static'
        env_file:
            - prod.env
        ports:
            - "127.0.0.1:8000:80"
        depends_on:
            - interactivemap
