# Generated by Django 2.0.1 on 2018-01-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Canonical name of the event')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Flavor text, Wikipedia, etc.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='When this border takes effect.')),
                ('end_date', models.DateField(help_text='When this border ceases to exist.')),
                ('end_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_event', to='mappy.Event')),
                ('start_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_event', to='mappy.Event')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Canonical name -- each state should have only one.')),
                ('aliases', models.TextField(blank=True, help_text='Other names this state may be known by.', null=True)),
                ('description', models.TextField(blank=True, help_text='Links, flavor text, etc.', null=True)),
                ('color', models.TextField(help_text='I expect this to be the most controversial field.')),
            ],
        ),
        migrations.AddField(
            model_name='shape',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mappy.State'),
        ),
        migrations.AddField(
            model_name='event',
            name='states',
            field=models.ManyToManyField(help_text='State(s) affected by this event.', to='mappy.State'),
        ),
    ]
