# Generated by Django 2.0.1 on 2018-02-11 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='shape',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.TextField(help_text='Canonical name -- each state should have only one.', unique=True),
        ),
    ]
